package es.svalero.leaguemanagement.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LeagueDay service. Represents a row in the &quot;LM_LeagueDay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.svalero.leaguemanagement.model.impl.LeagueDayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.svalero.leaguemanagement.model.impl.LeagueDayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeagueDay
 * @see es.svalero.leaguemanagement.model.impl.LeagueDayImpl
 * @see es.svalero.leaguemanagement.model.impl.LeagueDayModelImpl
 * @generated
 */
public interface LeagueDayModel extends BaseModel<LeagueDay>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a league day model instance should use the {@link LeagueDay} interface instead.
     */

    /**
     * Returns the primary key of this league day.
     *
     * @return the primary key of this league day
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this league day.
     *
     * @param primaryKey the primary key of this league day
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this league day.
     *
     * @return the uuid of this league day
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this league day.
     *
     * @param uuid the uuid of this league day
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the league day ID of this league day.
     *
     * @return the league day ID of this league day
     */
    public long getLeagueDayId();

    /**
     * Sets the league day ID of this league day.
     *
     * @param leagueDayId the league day ID of this league day
     */
    public void setLeagueDayId(long leagueDayId);

    /**
     * Returns the group ID of this league day.
     *
     * @return the group ID of this league day
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this league day.
     *
     * @param groupId the group ID of this league day
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this league day.
     *
     * @return the company ID of this league day
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this league day.
     *
     * @param companyId the company ID of this league day
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this league day.
     *
     * @return the user ID of this league day
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this league day.
     *
     * @param userId the user ID of this league day
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this league day.
     *
     * @return the user uuid of this league day
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this league day.
     *
     * @param userUuid the user uuid of this league day
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this league day.
     *
     * @return the user name of this league day
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this league day.
     *
     * @param userName the user name of this league day
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this league day.
     *
     * @return the create date of this league day
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this league day.
     *
     * @param createDate the create date of this league day
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this league day.
     *
     * @return the modified date of this league day
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this league day.
     *
     * @param modifiedDate the modified date of this league day
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the league ID of this league day.
     *
     * @return the league ID of this league day
     */
    public long getLeagueId();

    /**
     * Sets the league ID of this league day.
     *
     * @param leagueId the league ID of this league day
     */
    public void setLeagueId(long leagueId);

    /**
     * Returns the number of this league day.
     *
     * @return the number of this league day
     */
    @AutoEscape
    public String getNumber();

    /**
     * Sets the number of this league day.
     *
     * @param number the number of this league day
     */
    public void setNumber(String number);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(es.svalero.leaguemanagement.model.LeagueDay leagueDay);

    @Override
    public int hashCode();

    @Override
    public CacheModel<es.svalero.leaguemanagement.model.LeagueDay> toCacheModel();

    @Override
    public es.svalero.leaguemanagement.model.LeagueDay toEscapedModel();

    @Override
    public es.svalero.leaguemanagement.model.LeagueDay toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
