package es.svalero.leaguemanagement.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.svalero.leaguemanagement.model.LeagueDay;
import es.svalero.leaguemanagement.service.LeagueDayLocalServiceUtil;

/**
 * The extended model base implementation for the LeagueDay service. Represents a row in the &quot;LM_LeagueDay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeagueDayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeagueDayImpl
 * @see es.svalero.leaguemanagement.model.LeagueDay
 * @generated
 */
public abstract class LeagueDayBaseImpl extends LeagueDayModelImpl
    implements LeagueDay {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a league day model instance should use the {@link LeagueDay} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LeagueDayLocalServiceUtil.addLeagueDay(this);
        } else {
            LeagueDayLocalServiceUtil.updateLeagueDay(this);
        }
    }
}
