package es.svalero.leaguemanagement.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import es.svalero.leaguemanagement.model.Match;
import es.svalero.leaguemanagement.model.MatchModel;
import es.svalero.leaguemanagement.model.MatchSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Match service. Represents a row in the &quot;LM_Match&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link es.svalero.leaguemanagement.model.MatchModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MatchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatchImpl
 * @see es.svalero.leaguemanagement.model.Match
 * @see es.svalero.leaguemanagement.model.MatchModel
 * @generated
 */
@JSON(strict = true)
public class MatchModelImpl extends BaseModelImpl<Match> implements MatchModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a match model instance should use the {@link es.svalero.leaguemanagement.model.Match} interface instead.
     */
    public static final String TABLE_NAME = "LM_Match";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "matchId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "localTeamId", Types.BIGINT },
            { "visitingTeamId", Types.BIGINT },
            { "localScore", Types.INTEGER },
            { "visitingScore", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table LM_Match (uuid_ VARCHAR(75) null,matchId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,localTeamId LONG,visitingTeamId LONG,localScore INTEGER,visitingScore INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table LM_Match";
    public static final String ORDER_BY_JPQL = " ORDER BY match.matchId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY LM_Match.matchId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.es.svalero.leaguemanagement.model.Match"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.es.svalero.leaguemanagement.model.Match"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.es.svalero.leaguemanagement.model.Match"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UUID_COLUMN_BITMASK = 4L;
    public static long MATCHID_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.es.svalero.leaguemanagement.model.Match"));
    private static ClassLoader _classLoader = Match.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Match.class };
    private String _uuid;
    private String _originalUuid;
    private long _matchId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private long _localTeamId;
    private long _visitingTeamId;
    private int _localScore;
    private int _visitingScore;
    private long _columnBitmask;
    private Match _escapedModel;

    public MatchModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Match toModel(MatchSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Match model = new MatchImpl();

        model.setUuid(soapModel.getUuid());
        model.setMatchId(soapModel.getMatchId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setLocalTeamId(soapModel.getLocalTeamId());
        model.setVisitingTeamId(soapModel.getVisitingTeamId());
        model.setLocalScore(soapModel.getLocalScore());
        model.setVisitingScore(soapModel.getVisitingScore());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Match> toModels(MatchSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Match> models = new ArrayList<Match>(soapModels.length);

        for (MatchSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _matchId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setMatchId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _matchId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Match.class;
    }

    @Override
    public String getModelClassName() {
        return Match.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("matchId", getMatchId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("localTeamId", getLocalTeamId());
        attributes.put("visitingTeamId", getVisitingTeamId());
        attributes.put("localScore", getLocalScore());
        attributes.put("visitingScore", getVisitingScore());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long matchId = (Long) attributes.get("matchId");

        if (matchId != null) {
            setMatchId(matchId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Long localTeamId = (Long) attributes.get("localTeamId");

        if (localTeamId != null) {
            setLocalTeamId(localTeamId);
        }

        Long visitingTeamId = (Long) attributes.get("visitingTeamId");

        if (visitingTeamId != null) {
            setVisitingTeamId(visitingTeamId);
        }

        Integer localScore = (Integer) attributes.get("localScore");

        if (localScore != null) {
            setLocalScore(localScore);
        }

        Integer visitingScore = (Integer) attributes.get("visitingScore");

        if (visitingScore != null) {
            setVisitingScore(visitingScore);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getMatchId() {
        return _matchId;
    }

    @Override
    public void setMatchId(long matchId) {
        _matchId = matchId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public long getLocalTeamId() {
        return _localTeamId;
    }

    @Override
    public void setLocalTeamId(long localTeamId) {
        _localTeamId = localTeamId;
    }

    @JSON
    @Override
    public long getVisitingTeamId() {
        return _visitingTeamId;
    }

    @Override
    public void setVisitingTeamId(long visitingTeamId) {
        _visitingTeamId = visitingTeamId;
    }

    @JSON
    @Override
    public int getLocalScore() {
        return _localScore;
    }

    @Override
    public void setLocalScore(int localScore) {
        _localScore = localScore;
    }

    @JSON
    @Override
    public int getVisitingScore() {
        return _visitingScore;
    }

    @Override
    public void setVisitingScore(int visitingScore) {
        _visitingScore = visitingScore;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Match.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Match.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Match toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Match) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        MatchImpl matchImpl = new MatchImpl();

        matchImpl.setUuid(getUuid());
        matchImpl.setMatchId(getMatchId());
        matchImpl.setGroupId(getGroupId());
        matchImpl.setCompanyId(getCompanyId());
        matchImpl.setUserId(getUserId());
        matchImpl.setUserName(getUserName());
        matchImpl.setCreateDate(getCreateDate());
        matchImpl.setModifiedDate(getModifiedDate());
        matchImpl.setLocalTeamId(getLocalTeamId());
        matchImpl.setVisitingTeamId(getVisitingTeamId());
        matchImpl.setLocalScore(getLocalScore());
        matchImpl.setVisitingScore(getVisitingScore());

        matchImpl.resetOriginalValues();

        return matchImpl;
    }

    @Override
    public int compareTo(Match match) {
        long primaryKey = match.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Match)) {
            return false;
        }

        Match match = (Match) obj;

        long primaryKey = match.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        MatchModelImpl matchModelImpl = this;

        matchModelImpl._originalUuid = matchModelImpl._uuid;

        matchModelImpl._originalGroupId = matchModelImpl._groupId;

        matchModelImpl._setOriginalGroupId = false;

        matchModelImpl._originalCompanyId = matchModelImpl._companyId;

        matchModelImpl._setOriginalCompanyId = false;

        matchModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Match> toCacheModel() {
        MatchCacheModel matchCacheModel = new MatchCacheModel();

        matchCacheModel.uuid = getUuid();

        String uuid = matchCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            matchCacheModel.uuid = null;
        }

        matchCacheModel.matchId = getMatchId();

        matchCacheModel.groupId = getGroupId();

        matchCacheModel.companyId = getCompanyId();

        matchCacheModel.userId = getUserId();

        matchCacheModel.userName = getUserName();

        String userName = matchCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            matchCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            matchCacheModel.createDate = createDate.getTime();
        } else {
            matchCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            matchCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            matchCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        matchCacheModel.localTeamId = getLocalTeamId();

        matchCacheModel.visitingTeamId = getVisitingTeamId();

        matchCacheModel.localScore = getLocalScore();

        matchCacheModel.visitingScore = getVisitingScore();

        return matchCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", matchId=");
        sb.append(getMatchId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", localTeamId=");
        sb.append(getLocalTeamId());
        sb.append(", visitingTeamId=");
        sb.append(getVisitingTeamId());
        sb.append(", localScore=");
        sb.append(getLocalScore());
        sb.append(", visitingScore=");
        sb.append(getVisitingScore());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append("es.svalero.leaguemanagement.model.Match");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>matchId</column-name><column-value><![CDATA[");
        sb.append(getMatchId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>localTeamId</column-name><column-value><![CDATA[");
        sb.append(getLocalTeamId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>visitingTeamId</column-name><column-value><![CDATA[");
        sb.append(getVisitingTeamId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>localScore</column-name><column-value><![CDATA[");
        sb.append(getLocalScore());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>visitingScore</column-name><column-value><![CDATA[");
        sb.append(getVisitingScore());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
