package es.svalero.leaguemanagement.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.svalero.leaguemanagement.model.Match;
import es.svalero.leaguemanagement.service.MatchLocalServiceUtil;

/**
 * The extended model base implementation for the Match service. Represents a row in the &quot;LM_Match&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MatchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatchImpl
 * @see es.svalero.leaguemanagement.model.Match
 * @generated
 */
public abstract class MatchBaseImpl extends MatchModelImpl implements Match {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a match model instance should use the {@link Match} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MatchLocalServiceUtil.addMatch(this);
        } else {
            MatchLocalServiceUtil.updateMatch(this);
        }
    }
}
