package es.svalero.leaguemanagement.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.svalero.leaguemanagement.model.Team;
import es.svalero.leaguemanagement.service.TeamLocalServiceUtil;

/**
 * The extended model base implementation for the Team service. Represents a row in the &quot;LM_Team&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamImpl
 * @see es.svalero.leaguemanagement.model.Team
 * @generated
 */
public abstract class TeamBaseImpl extends TeamModelImpl implements Team {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a team model instance should use the {@link Team} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TeamLocalServiceUtil.addTeam(this);
        } else {
            TeamLocalServiceUtil.updateTeam(this);
        }
    }
}
